# Generated by Django 4.2.1 on 2023-12-24 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('song_artist', models.CharField(max_length=100)),
                ('song_lyrics', models.TextField()),
                ('song_image_url', models.URLField()),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], max_length=10)),
                ('type', models.CharField(choices=[('Song Lyrics', 'Song Lyrics'), ('Poetry', 'Poetry'), ('Quote', 'Quote')], max_length=20)),
                ('tags', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lyrics',
            },
        ),
    ]
